[model_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "/workspace/parrot-host/app/services/ai_services/lora_trainer/pretrained_model/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9"
vae = "/workspace/parrot-host/app/services/ai_services/lora_trainer/pretrained_model/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9/vae"

[additional_network_arguments]
no_metadata = false
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "networks.lora"
network_dim = 32
network_alpha = 32
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "Adafactor"
learning_rate = 0.0001
max_grad_norm = 1.0
lr_scheduler = "constant"
lr_warmup_steps = 0

[dataset_arguments]
cache_latents = true
debug_dataset = false

[training_arguments]
output_dir = "/workspace/parrot-host/app/services/ai_services/lora_trainer/tmp/415324b4-357f-4bc7-bff0-b7624e539910"
output_name = "415324b4-357f-4bc7-bff0-b7624e539910"
save_precision = "fp16"
save_every_n_epochs = 2
train_batch_size = 6
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 2
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = false
gradient_accumulation_steps = 1
mixed_precision = "fp16"
clip_skip = 1
logging_dir = "/workspace/parrot-host/app/services/ai_services/lora_trainer/LoRA/logs"
log_prefix = "415324b4-357f-4bc7-bff0-b7624e539910"
lowram = true
no_half_vae = false

[sample_prompt_arguments]
sample_every_n_epochs = 2
sample_sampler = "euler_a"

[dreambooth_arguments]
prior_loss_weight = 1.0

[saving_arguments]
save_model_as = "safetensors"
